name-template: v$NEXT_MAJOR_VERSION
tag_template: v$NEXT_MAJOR_VERSION
prerelease: true
exclude-labels:
  - skip-changelog

categories:
  - title: Features
    labels:
      - new-feature
  - title: Bug Fixes
    labels:
      - bug-report
  - title: Stylus
    labels:
      - stylus
  - title: TypeScript
    labels:
      - typescript
  - title: Accessibility
    labels:
      - accessibility
  - title: Misc
    labels:
      - build
      - meta
      - chore
  - title: Dependences
    labels:
      - dependences

change-template: '- #$NUMBER: $TITLE'
template: |
  ## Changes
  $CHANGES
