version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:latest-node

jobs:
  install_python_deps:
    executor: python
    steps:
      - checkout
      - restore_cache:
          key: v1-chichi-pydeps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths: ~/
      - run: pipenv install
      - save_cache:
          key: v1-chichi-pydeps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths: ~/

  install_node_deps:
    executor: python
    steps:
      - checkout
      - restore_cache:
          key: v1-chichi-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: ~/
      - run: yarn install
      - save_cache:
          key: v1-chichi-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: ~/
workflows:
  version: 2
  build:
    jobs:
      - install_python_deps:
        pre_steps:
          run: pip3 install pipenv

      - install_node_deps
